name: super_text_layout
description: Configurable, composable, extensible text display for Flutter.
version: 0.1.8
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text:
    git:
      url: https://github.com/soraschools/super_editor
      path: attributed_text
      ref: 0fcc701dc2adca09d89c3181c766b110cbd14ea1
  collection: ^1.18.0
  logging: ^1.0.1

  # For inspector
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  attributed_text:
    path: ../attributed_text

dev_dependencies:
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0
  args: ^2.3.1
  meta: ^1.8.0
  golden_runner:
    path: ../golden_runner

flutter:
  # no Flutter configuration
